version: 0.2
phases: 
    install:
        runtime-versions:
            nodejs: 22.9.0
        commands:
            - npm i npm@latest -g
    pre_build:
        commands:
            - npm install
    build:
        commands:
            - npm run build
    post_build:
        commands:
            - aws codebuild-sample-pangwoo sync ./dist codebuild-sample-pangwoo://codebuild-sample-test